version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/mikrotik-hotspot-oauth # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.2-node

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run:
          name: install hotspot ui
          command: cd source && npm i
      - run:
          name: build hotspot ui
          command: cd source && npm run lint
      - run:
          name: build hotspot ui
          command: cd source && npm run build
